### ISSUE TITLE
Catch a merge

### ISSUE THREAD

**Issue by emsesc** [bitprj/counselor#14]
Stop a student from merging or closing an issue when they're not supposed to

**Comment by emsesc** [comment]
> I had a thought, to prevent students merging thier PRs at the wrong time  could it be possible to make the student repos require the bot as an approver on the PRs and only allow merge once approved or maybe auto merge. The bot at the correct time can approve the PR preventing early merges?

https://octokit.github.io/octokit.rb/Octokit/Client/Reviews.html
https://octokit.github.io/rest.js/v18#repos-set-admin-branch-protection

**Comment by ganning127** [comment]
protected main branch to solve this
