### ISSUE TITLE
Call the serverless function in a javascript file in a repository

### ISSUE THREAD

**Issue by emsesc** [bitprj/counselor#28]
> **Add to bot code:** Get user's username and repo name and store in repository secrets so they can be accessed in this JS file

When you run the file, it will call the serverless function and return the count value (progress)

❗ Accept the parameters for the function from the commandline
❗ This file should be committed on the curriculum repo

**Comment by emsesc** [comment]
https://octokit.github.io/rest.js/v18#actions-create-or-update-repo-secret

**Comment by ganning127** [comment]
https://stackoverflow.com/questions/4351521/how-do-i-pass-command-line-arguments-to-a-node-js-program
