### ISSUE TITLE
Create public REST API endpoint to get student progress data based on username and repo name

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/counselor#41]
Create public REST API endpoint to get student progress data based on username and repo name

https://hasura.io/blog/adding-rest-endpoints-to-hasura-cloud/
https://www.youtube.com/watch?time_continue=1080&v=vy4iXukXc8Y&feature=emb_title

**Comment by ganning127** [comment]
@emsesc is this just the hasura function that takes in username & repo name and returns count?

**Comment by emsesc** [comment]
@ganning127 Yep!
